# Brave Search API Configuration
# Get your API key from: https://brave.com/search/api/

brave_search:
  # IMPORTANT: Replace with your actual Brave Search API key
  api_key: "YOUR_BRAVE_API_KEY_HERE"

  # API base URL (typically doesn't need to be changed)
  base_url: "https://api.search.brave.com/res/v1"

  # Rate limiting (Brave API has 1 request/second limit)
  rate_limit:
    requests_per_second: 0.9  # Set slightly below 1.0 for safety margin

  # Archive settings
  enable_archive: true
  archive_path: "./archives"
